In [16]:
import pandas as pd

In [72]:
df = pd.DataFrame([
    ["C001", "製造業", 30],
    ["C002", "サービス業", 100.12],
    ["C003", "サービス業", None],
    ["C004", "小売業", 50],
    ["C005", "製造業", 20]
    ], columns=["会社コード", "業種", "従業員数"]
)

In [42]:
pd.set_option("display.precision", 3)

In [73]:
df.iloc[2:4, 0:]

  会社コード     業種  従業員数
2  C003  サービス業   NaN
3  C004    小売業  50.0

In [67]:
df.query("業種 != '製造業' and 従業員数 >= 30")[["会社コード", "業種", "従業員数"]]

  会社コード     業種    従業員数
1  C002  サービス業  100.12
3  C004    小売業   50.00

In [65]:
df.assign(**{"フラグ": 0})

  会社コード     業種    従業員数  フラグ
0  C001    製造業   30.00    0
1  C002  サービス業  100.12    0
2  C003  サービス業     NaN    0
3  C004    小売業   50.00    0
4  C005    製造業   20.00    0

In [70]:
df_original = df.copy()
df["フランス"] = 0
df.loc[df["従業員数"] >= 30, "フランス"] = 1
df

  会社コード     業種    従業員数  フランス
0  C001    製造業   30.00     1
1  C002  サービス業  100.12     1
2  C003  サービス業     NaN     0
3  C004    小売業   50.00     1
4  C005    製造業   20.00     0

In [71]:
df[df["従業員数"].notna()]

  会社コード     業種    従業員数  フランス
0  C001    製造業   30.00     1
1  C002  サービス業  100.12     1
3  C004    小売業   50.00     1
4  C005    製造業   20.00     0

In [ ]:
import numpy as np
dfll = pd.DataFrame([
    ["a", "x", 2],
    ["a", "y", 2]

])